package kubeapiserver

var pediaClusterTemp = `
{
	"apiVersion":"cluster.clusterpedia.io/v1alpha2",
	"kind":"PediaCluster",
	"metadata":{
	    "name":"global-cluster"
	},
	"spec":{
	    "syncResources":[
		   {
			  "group":"",
			  "resources":[
				 "pods",
				 "nodes",
				 "namespaces",
				 "configmaps",
				 "services",
				 "events",
				 "secrets",
				 "persistentvolumeclaims",
				 "persistentvolumes"
			  ],
			  "versions":[
				 "v1"
			  ]
		   },
		   {
			  "group":"apps",
			  "resources":[
				 "deployments",
				 "statefulsets",
				 "replicasets",
				 "daemonsets",
				 "controllerrevisions"
			  ],
			  "versions":[
				 "v1"
			  ]
		   },
		   {
			  "group":"batch",
			  "resources":[
				 "jobs",
				 "cronjobs"
			  ],
			  "versions":[
				 "v1"
			  ]
		   },
		   {
			  "group":"rbac.authorization.k8s.io",
			  "resources":[
				 "clusterrolebindings",
				 "rolebindings",
				 "clusterroles",
				 "roles"
			  ],
			  "versions":[
				 "v1"
			  ]
		   },
		   {
			"group":"snapshot.storage.k8s.io",
			"resources":[
			   "volumesnapshotclasses",
			   "volumesnapshotcontents",
			   "volumesnapshots"
			],
			"versions":[
			   "v1"
			]
		   },
		   {
			"group":"storage.k8s.io",
			"resources":[
			   "storageclasses"
			],
			"versions":[
			   "v1"
			]
		   },
		   {
			"group":"autoscaling",
			"resources":[
			   "horizontalpodautoscalers"
			],
			"versions":[
			   "v1"
			]
		   },
		   {
			  "group":"networking.k8s.io",
			  "resources":[
				 "ingresses",
				 "ingressclasses"
			  ],
			  "versions":[
				 "v1"
			  ]
		   },
		   {
			  "group":"apiextensions.k8s.io",
			  "resources":[
				 "customresourcedefinitions"
			  ],
			  "versions":[
				 "v1"
			  ]
		   },
		   {
			  "group":"cluster.kpanda.io",
			  "resources":[
				 "clusters"
			  ],
			  "versions":[
				 "v1alpha1"
			  ]
		   },
		   {
			  "group":"cluster.kpanda.io",
			  "resources":[
				 "clusters"
			  ],
			  "versions":[
				 "v1alpha1"
			  ]
		   }
	    ]
	},
	"status":{
	    "conditions":[
		   {
			  "message":"",
			  "reason":"Healthy",
			  "status":"True",
			  "type":"Ready"
		   }
	    ],
	    "syncResources":[
		   {
			  "group":"",
			  "resources":[
				 {
					"kind":"Pod",
					"name":"pods",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"Node",
					"name":"nodes",
					"namespaced":false,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"Namespace",
					"name":"namespaces",
					"namespaced":false,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"ConfigMap",
					"name":"configmaps",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"Service",
					"name":"services",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"Event",
					"name":"events",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"Secret",
					"name":"secrets",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"PersistentVolumeClaim",
					"name":"persistentvolumeclaims",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"PersistentVolume",
					"name":"persistentvolumes",
					"namespaced":false,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 }
			  ]
		   },
		   {
			  "group":"apps",
			  "resources":[
				 {
					"kind":"Deployment",
					"name":"deployments",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"StatefulSet",
					"name":"statefulsets",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"ReplicaSet",
					"name":"replicasets",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"DaemonSet",
					"name":"daemonsets",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"ControllerRevision",
					"name":"controllerrevisions",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 }
			  ]
		   },
		   {
			  "group":"batch",
			  "resources":[
				 {
					"kind":"Job",
					"name":"jobs",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"CronJob",
					"name":"cronjobs",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 }
			  ]
		   },
		   {
			  "group":"rbac.authorization.k8s.io",
			  "resources":[
				 {
					"kind":"ClusterRoleBinding",
					"name":"clusterrolebindings",
					"namespaced":false,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"RoleBinding",
					"name":"rolebindings",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"ClusterRole",
					"name":"clusterroles",
					"namespaced":false,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"Role",
					"name":"roles",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 }
			  ]
		   },
		   {
			  "group":"networking.k8s.io",
			  "resources":[
				 {
					"kind":"Ingress",
					"name":"ingresses",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 },
				 {
					"kind":"IngressClass",
					"name":"ingressclasses",
					"namespaced":false,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 }
			  ]
		   },
		   {
			"group":"snapshot.storage.k8s.io",
			"resources":[
			   {
				  "kind":"VolumeSnapshot",
				  "name":"volumesnapshots",
				  "namespaced":true,
				  "syncConditions":[
					  {
						 "status":"Syncing",
						 "storageVersion":"v1",
						 "version":"v1"
					  }
				  ]
			   },
			   {
				  "kind":"VolumeSnapshotContent",
				  "name":"volumesnapshotcontents",
				  "namespaced":false,
				  "syncConditions":[
					  {
						 "status":"Syncing",
						 "storageVersion":"v1",
						 "version":"v1"
					  }
				  ]
			   },
			   {
				"kind":"VolumeSnapshotClass",
				"name":"volumesnapshotclasses",
				"namespaced":false,
				"syncConditions":[
					{
					   "status":"Syncing",
					   "storageVersion":"v1",
					   "version":"v1"
					}
				]
			 }
			]
		 },
		 {
			"group":"storage.k8s.io",
			"resources":[
			   {
				  "kind":"StorageClass",
				  "name":"storageclasses",
				  "namespaced":true,
				  "syncConditions":[
					  {
						 "status":"Syncing",
						 "storageVersion":"v1",
						 "version":"v1"
					  }
				  ]
			   }
			]
		 },
		   {
			  "group":"autoscaling",
			  "resources":[
				 {
					"kind":"HorizontalPodAutoscaler",
					"name":"horizontalpodautoscalers",
					"namespaced":true,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1",
						   "version":"v1"
					    }
					]
				 }
			  ]
		   },
		   {
			"group":"apiextensions.k8s.io",
			"resources":[
			   {
				  "kind":"CustomResourceDefinition",
				  "name":"customresourcedefinitions",
				  "namespaced":false,
				  "syncConditions":[
					  {
						 "status":"Syncing",
						 "storageVersion":"v1",
						 "version":"v1"
					  }
				  ]
			   }
			]
		 },
		   {
			  "group":"cluster.kpanda.io",
			  "resources":[
				 {
					"kind":"Cluster",
					"name":"clusters",
					"namespaced":false,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1alpha1",
						   "version":"v1alpha1"
					    }
					]
				 },
				 {
					"kind":"Cluster",
					"name":"clusters",
					"namespaced":false,
					"syncConditions":[
					    {
						   "status":"Syncing",
						   "storageVersion":"v1alpha1",
						   "version":"v1alpha1"
					    }
					]
				 }
			  ]
		   }
	    ]
	}
 }
`
